version: '3'
services:
  web:
    build: .
    volumes:
      - .:/code/src
    command: >
      bash -c "gulp &
      rsync -arv --delete /code/vendor /code/node_modules /code/composer.lock /code/package-lock.json /code/src &
      ./init --env=Development --overwrite=n &&
      service nginx start &&
      php-fpm"
  mariadb:
    image: mariadb:10.5.12
  redis:
    image: redis:6.0.16
  elasticsearch:
    image: elasticsearch:5.6.16
