version: '3'
services:
  web:
    build: .
    volumes:
      - web_volume:/code/web
    expose:
      - 9000
    command: >
      bash -c "./init --env=Development --overwrite=n &&
      php-fpm"
  mariadb:
    image: mariadb:10.5.12
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: yiiframeworkcom
      MYSQL_USER: yiiframeworkcom
      MYSQL_PASSWORD: yiiframeworkcom
  nginx:
    build:
      context: docker/nginx
    volumes:
      - web_volume:/code/web
    ports:
      - 81:81
    depends_on:
      - web
  redis:
    image: redis:6.0.16
  elasticsearch:
    image: elasticsearch:5.6.16
    ports:
      - "9200:9200"
volumes:
  web_volume:
